server {
    # Listen for all incomming request at port 80 (HTTP)
    listen 80 default_server;

    # Listen to all incomming request targetting 127.0.0.1 or localhost;
    server_name 127.0.0.1 localhost;

    # For all incomming request without exceptions
    location ~ / {
        # Serve static files from this folder
        root /usr/share/nginx/html;

        # Try to access the requested uri
        # Or try to access the request uri folder
        # Or try to access the index.html file from the root folder
        # Or trigger a 404 page
        try_files $uri $uri/ /index.html = 404;
    } 
}
