name: Elm CI

on:
    push:
        branches:
            - latest

    pull_request:
        branches:
            - latest

jobs:
    elm-format:
        runs-on: ubuntu-latest
        name: Elm Format

        steps:
            - name: Git Checkout
              uses: actions/checkout@v2

            - name: Node Setup
              uses: actions/setup-node@v2

            - name: Dependencies installation
              run: npm install

            - name: Elm Syntax Validation
              run: make format
